export const LIQUIDATOR = '8kmSBtXyQ5svS8qPiHLA5BTrQ2iUN86KATKn2EJUEpen';
export const LIQUIDATOR_POOL = 'FgtZAHSSycjA8iaph478raui8te4jVFF3Bn7KXHkVjCT';
export const CONTROLLER_SEED = 'CONTROLLER';
export const REDEEMABLE_MINT_SEED = 'REDEEMABLE';
export const LIQUIDATOR_POOL_NAMESPACE = 'LIQUIDATOR_POOL';
export const LP_PROVIDER_NAMESPACE = 'LP_PROVIDER';
